In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import plotly as px
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r"C:\Users\Mansi\Downloads\7472_source_data.csv")

In [3]:
df.head()

,Country,srcYear,Type of scheduled commercial banks,Bank name,Cash in hand,Balances with Reserve Bank of India(RBI),Balances with banks in India,Money at call and short notice,Balances with banks outside India,Investments,...,Premises by fixed assets,Fixed assets under construction,Other fixed assets,Other assets,Net inter-office adjustments by other assets,Interest accrued,Tax paid by other assets,Stationery and Stamps by other assets,Others by other assets,Total assets
0,India,2023-24,FOREIGN BANKS,AB BANK LIMITED,0.395063,6.236989,121.908369,NaN,151.728852,74.26462,...,NaN,NaN,0.341193,13.292653,0.004535,3.629779,0.128255,0.008464,9.521620,436.387817
1,India,2023-24,FOREIGN BANKS,AMERICAN EXPRESS BANKING CORP.,NaN,363.050800,6.175600,NaN,NaN,4609.90750,...,NaN,NaN,388.151100,1027.402100,NaN,17.302400,95.484600,NaN,914.615100,11113.410200
2,India,2023-24,FOREIGN BANKS,AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED,0.076700,429.032300,585.548900,NaN,602.421500,17757.72550,...,NaN,NaN,27.814900,4658.739000,NaN,232.410900,81.717500,16.311500,4328.299100,27939.114900
3,India,2023-24,FOREIGN BANKS,"BANK OF AMERICA , NATIONAL ASSOCIATION",3.566503,3960.120205,16.268482,4255.612041,68.045508,60159.60979,...,NaN,18.422394,159.371303,10705.003340,NaN,722.582426,197.483168,NaN,9784.937748,106784.003400
4,India,2023-24,FOREIGN BANKS,BANK OF BAHRAIN & KUWAIT B.S.C.,1.162100,92.236000,2.798600,285.610600,53.116900,529.45280,...,16.56,0.194600,4.633400,137.968700,NaN,11.382800,5.633500,0.000600,120.951800,2558.061900

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1775 entries, 0 to 1774
Data columns (total 45 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   Country                                                          1775 non-null   object
 1   srcYear                                                          1775 non-null   object
 2   Type of scheduled commercial banks                               1775 non-null   object
 3   Bank name                                                        1775 non-null   object
 4   Cash in hand                                                     1666 non-null   float64
 5   Balances with Reserve Bank of India(RBI)                         1775 non-null   float64
 6   Balances with banks in India                                     1770 non-null   float64
 7   Money at call and short notice                                   1206 non-null   float64
 8   Balances with banks outside India                                1599 non-null   float64
 9   Investments                                                      1740 non-null   float64
 10  Investments in India                                             1740 non-null   float64
 11  Investments on government securities in India                    1735 non-null   float64
 12  Investments on approved securities in India                      539 non-null    float64
 13  Investments on shares in India                                   1109 non-null   float64
 14  Investments on debentures and bonds in India                     1198 non-null   float64
 15  Investments on subsidiaries and/or joint ventures in India       607 non-null    float64
 16  Other investments in India                                       1296 non-null   float64
 17  Investments outside India                                        437 non-null    float64
 18  Investments on government securities outside India               259 non-null    float64
 19  Investments on subsidiaries and/or joint ventures outside India  201 non-null    float64
 20  Other investments outside India                                  356 non-null    float64
 21  Advances                                                         1717 non-null   float64
 22  Bills purchased and discounted                                   1526 non-null   float64
 23  Cash credits, overdrafts and loans                               1661 non-null   float64
 24  Term loans                                                       1662 non-null   float64
 25  Advances secured by tangible assets                              1661 non-null   float64
 26  Advances covered by bank or government guarantees                1318 non-null   float64
 27  Unsecured advances                                               1653 non-null   float64
 28  Advances in India                                                1717 non-null   float64
 29  Advances in priority sectors in India                            1646 non-null   float64
 30  Advances in public sectors in India                              1012 non-null   float64
 31  Advances in banks in India                                       881 non-null    float64
 32  Other advances in India                                          1704 non-null   float64
 33  Advances outside India                                           321 non-null    float64
 34  Fixed assets                                                     1764 non-null   float64
 35  Premises by fixed assets                                         1268 non-null   float64
 36  Fixed assets under construction                                  877 non-null    float64
 37  Other fixed assets                                               1755 non-null   float64
 38  Other assets                                                     1775 non-null   float64
 39  Net inter-office adjustments by other assets                     393 non-null    float64
 40  Interest accrued                                                 1764 non-null   float64
 41  Tax paid by other assets                                         1598 non-null   float64
 42  Stationery and Stamps by other assets                            1170 non-null   float64
 43  Others by other assets                                           1774 non-null   float64
 44  Total assets                                                     1775 non-null   float64
dtypes: float64(41), object(4)
memory usage: 624.2+ KB

In [5]:
missing_peecent = (df.isnull().sum()/len(df)*100)

In [6]:
missing_summury = pd.DataFrame({
    'Missing Values' : df.isnull().sum(),
    'Missing %' : df.isnull().sum()/len(df)*100
})

In [7]:
missing_summury

                                                    Missing Values  Missing %
Country                                                          0   0.000000
srcYear                                                          0   0.000000
Type of scheduled commercial banks                               0   0.000000
Bank name                                                        0   0.000000
Cash in hand                                                   109   6.140845
Balances with Reserve Bank of India(RBI)                         0   0.000000
Balances with banks in India                                     5   0.281690
Money at call and short notice                                 569  32.056338
Balances with banks outside India                              176   9.915493
Investments                                                     35   1.971831
Investments in India                                            35   1.971831
Investments on government securities in India                   40   2.253521
Investments on approved securities in India                   1236  69.633803
Investments on shares in India                                 666  37.521127
Investments on debentures and bonds in India                   577  32.507042
Investments on subsidiaries and/or joint ventur...            1168  65.802817
Other investments in India                                     479  26.985915
Investments outside India                                     1338  75.380282
Investments on government securities outside India            1516  85.408451
Investments on subsidiaries and/or joint ventur...            1574  88.676056
Other investments outside India                               1419  79.943662
Advances                                                        58   3.267606
Bills purchased and discounted                                 249  14.028169
Cash credits, overdrafts and loans                             114   6.422535
Term loans                                                     113   6.366197
Advances secured by tangible assets                            114   6.422535
Advances covered by bank or government guarantees              457  25.746479
Unsecured advances                                             122   6.873239
Advances in India                                               58   3.267606
Advances in priority sectors in India                          129   7.267606
Advances in public sectors in India                            763  42.985915
Advances in banks in India                                     894  50.366197
Other advances in India                                         71   4.000000
Advances outside India                                        1454  81.915493
Fixed assets                                                    11   0.619718
Premises by fixed assets                                       507  28.563380
Fixed assets under construction                                898  50.591549
Other fixed assets                                              20   1.126761
Other assets                                                     0   0.000000
Net inter-office adjustments by other assets                  1382  77.859155
Interest accrued                                                11   0.619718
Tax paid by other assets                                       177   9.971831
Stationery and Stamps by other assets                          605  34.084507
Others by other assets                                           1   0.056338
Total assets                                                     0   0.000000

In [8]:
 missing_summury[missing_summury['Missing %'] > 30]

                                                    Missing Values  Missing %
Money at call and short notice                                 569  32.056338
Investments on approved securities in India                   1236  69.633803
Investments on shares in India                                 666  37.521127
Investments on debentures and bonds in India                   577  32.507042
Investments on subsidiaries and/or joint ventur...            1168  65.802817
Investments outside India                                     1338  75.380282
Investments on government securities outside India            1516  85.408451
Investments on subsidiaries and/or joint ventur...            1574  88.676056
Other investments outside India                               1419  79.943662
Advances in public sectors in India                            763  42.985915
Advances in banks in India                                     894  50.366197
Advances outside India                                        1454  81.915493
Fixed assets under construction                                898  50.591549
Net inter-office adjustments by other assets                  1382  77.859155
Stationery and Stamps by other assets                          605  34.084507

low importance feature 
1.Investments outside India
2.Investments on government securities outside India
3.Investments on subsidiaries and/or joint ventures outside India
4.Other investments outside India
5.Advances outside India
6.Net inter-office adjustments by other assets
7.Investments on approved securities in India
8.Investments on subsidiaries and/or joint ventures in India

In [9]:
df.columns = df.columns.str.strip()
print(df.columns.tolist())

['Country', 'srcYear', 'Type of scheduled commercial banks', 'Bank name', 'Cash in hand', 'Balances with Reserve Bank of India(RBI)', 'Balances with banks in India', 'Money at call and short notice', 'Balances with banks outside India', 'Investments', 'Investments in India', 'Investments on government securities in India', 'Investments on approved securities in India', 'Investments on shares in India', 'Investments on debentures and bonds in India', 'Investments on subsidiaries and/or joint ventures in India', 'Other investments in India', 'Investments outside India', 'Investments on government securities outside India', 'Investments on subsidiaries and/or joint ventures outside India', 'Other investments outside India', 'Advances', 'Bills purchased and discounted', 'Cash credits, overdrafts and loans', 'Term loans', 'Advances secured by tangible assets', 'Advances covered by bank or government guarantees', 'Unsecured advances', 'Advances in India', 'Advances in priority sectors in India', 'Advances in public sectors in India', 'Advances in banks in India', 'Other advances in India', 'Advances outside India', 'Fixed assets', 'Premises by fixed assets', 'Fixed assets under construction', 'Other fixed assets', 'Other assets', 'Net inter-office adjustments by other assets', 'Interest accrued', 'Tax paid by other assets', 'Stationery and Stamps by other assets', 'Others by other assets', 'Total assets']

In [10]:
df.drop([
'Investments outside India',
'Investments on government securities outside India',
'Investments on subsidiaries and/or joint ventures outside India',
'Other investments outside India',
'Advances outside India',
'Net inter-office adjustments by other assets',
'Investments on approved securities in India',
'Investments on subsidiaries and/or joint ventures in India',],axis=1,inplace=True)

In [11]:
df.isnull().sum()/len(df)*100

Country                                               0.000000
srcYear                                               0.000000
Type of scheduled commercial banks                    0.000000
Bank name                                             0.000000
Cash in hand                                          6.140845
Balances with Reserve Bank of India(RBI)              0.000000
Balances with banks in India                          0.281690
Money at call and short notice                       32.056338
Balances with banks outside India                     9.915493
Investments                                           1.971831
Investments in India                                  1.971831
Investments on government securities in India         2.253521
Investments on shares in India                       37.521127
Investments on debentures and bonds in India         32.507042
Other investments in India                           26.985915
Advances                                              3.267606
Bills purchased and discounted                       14.028169
Cash credits, overdrafts and loans                    6.422535
Term loans                                            6.366197
Advances secured by tangible assets                   6.422535
Advances covered by bank or government guarantees    25.746479
Unsecured advances                                    6.873239
Advances in India                                     3.267606
Advances in priority sectors in India                 7.267606
Advances in public sectors in India                  42.985915
Advances in banks in India                           50.366197
Other advances in India                               4.000000
Fixed assets                                          0.619718
Premises by fixed assets                             28.563380
Fixed assets under construction                      50.591549
Other fixed assets                                    1.126761
Other assets                                          0.000000
Interest accrued                                      0.619718
Tax paid by other assets                              9.971831
Stationery and Stamps by other assets                34.084507
Others by other assets                                0.056338
Total assets                                          0.000000
dtype: float64

In [12]:
df['Cash in hand'] =  df['Cash in hand'].fillna(df['Cash in hand'].mean())

In [13]:
df['Money at call and short notice'] = df['Money at call and short notice'].fillna(df['Money at call and short notice'].median())

In [14]:
df['Other fixed assets'] =  df['Other fixed assets'].fillna(df['Other fixed assets'].mean())

In [15]:


df['Interest accrued'] = df['Interest accrued'].fillna(
    df['Interest accrued'].mean()
)

df['Tax paid by other assets'] = df['Tax paid by other assets'].fillna(
    df['Tax paid by other assets'].mean()
)

In [16]:
df['Stationery and Stamps by other assets'] = df['Stationery and Stamps by other assets'].fillna(
    df['Stationery and Stamps by other assets'].median()
)

In [17]:
df['Others by other assets'] = df['Others by other assets'].fillna(
    df['Others by other assets'].mean()
)

In [18]:
df['Balances with banks in India'] = df['Balances with banks in India'].fillna(
    df['Balances with banks in India'].mean()
)

In [19]:
df['Balances with banks outside India'] = df['Balances with banks outside India'].fillna(df['Balances with banks outside India'].mean())

df['Investments'] = df['Investments'].fillna(df['Investments'].mean())

df['Investments in India'] = df['Investments in India'].fillna(df['Investments in India'].mean())

df['Investments on government securities in India'] = df['Investments on government securities in India'].fillna(df['Investments on government securities in India'].mean())

In [20]:
# Fill missing values based on percentage

# Higher missing % → use median
df['Investments on shares in India'] = df['Investments on shares in India'].fillna(
    df['Investments on shares in India'].median()
)

df['Investments on debentures and bonds in India'] = df['Investments on debentures and bonds in India'].fillna(
    df['Investments on debentures and bonds in India'].median()
)

# Lower missing % → use mean
df['Other investments in India'] = df['Other investments in India'].fillna(
    df['Other investments in India'].mean()
)

In [21]:
# Fill missing values with mean

df['Advances'] = df['Advances'].fillna(df['Advances'].mean())

df['Bills purchased and discounted'] = df['Bills purchased and discounted'].fillna(
    df['Bills purchased and discounted'].mean()
)

df['Cash credits, overdrafts and loans'] = df['Cash credits, overdrafts and loans'].fillna(
    df['Cash credits, overdrafts and loans'].mean()
)

df['Term loans'] = df['Term loans'].fillna(
    df['Term loans'].mean()
)

df['Advances secured by tangible assets'] = df['Advances secured by tangible assets'].fillna(
    df['Advances secured by tangible assets'].mean()
)

df['Advances covered by bank or government guarantees'] = df['Advances covered by bank or government guarantees'].fillna(
    df['Advances covered by bank or government guarantees'].mean()
)

df['Unsecured advances'] = df['Unsecured advances'].fillna(
    df['Unsecured advances'].mean()
)

df['Advances in India'] = df['Advances in India'].fillna(
    df['Advances in India'].mean()
)

df['Advances in priority sectors in India'] = df['Advances in priority sectors in India'].fillna(
    df['Advances in priority sectors in India'].mean()
)

In [22]:
df['Advances in public sectors in India'] = df['Advances in public sectors in India'].fillna(
    df['Advances in public sectors in India'].median()
)

df['Advances in banks in India'] = df['Advances in banks in India'].fillna(
    df['Advances in banks in India'].median()
)

In [23]:
df['Fixed assets under construction'] = df['Fixed assets under construction'].fillna(
    df['Fixed assets under construction'].median()
)

In [24]:
# Fill missing values with mean

df['Other advances in India'] = df['Other advances in India'].fillna(
    df['Other advances in India'].mean()
)

df['Fixed assets'] = df['Fixed assets'].fillna(
    df['Fixed assets'].mean()
)

df['Premises by fixed assets'] = df['Premises by fixed assets'].fillna(
    df['Premises by fixed assets'].mean()
)

In [25]:
# Fill missing values with mean

df['Other advances in India'] = df['Other advances in India'].fillna(
    df['Other advances in India'].mean()
)

df['Fixed assets'] = df['Fixed assets'].fillna(
    df['Fixed assets'].mean()
)

df['Premises by fixed assets'] = df['Premises by fixed assets'].fillna(
    df['Premises by fixed assets'].mean()
)

In [26]:
df.isnull().sum()/len(df)*100

Country                                              0.0
srcYear                                              0.0
Type of scheduled commercial banks                   0.0
Bank name                                            0.0
Cash in hand                                         0.0
Balances with Reserve Bank of India(RBI)             0.0
Balances with banks in India                         0.0
Money at call and short notice                       0.0
Balances with banks outside India                    0.0
Investments                                          0.0
Investments in India                                 0.0
Investments on government securities in India        0.0
Investments on shares in India                       0.0
Investments on debentures and bonds in India         0.0
Other investments in India                           0.0
Advances                                             0.0
Bills purchased and discounted                       0.0
Cash credits, overdrafts and loans                   0.0
Term loans                                           0.0
Advances secured by tangible assets                  0.0
Advances covered by bank or government guarantees    0.0
Unsecured advances                                   0.0
Advances in India                                    0.0
Advances in priority sectors in India                0.0
Advances in public sectors in India                  0.0
Advances in banks in India                           0.0
Other advances in India                              0.0
Fixed assets                                         0.0
Premises by fixed assets                             0.0
Fixed assets under construction                      0.0
Other fixed assets                                   0.0
Other assets                                         0.0
Interest accrued                                     0.0
Tax paid by other assets                             0.0
Stationery and Stamps by other assets                0.0
Others by other assets                               0.0
Total assets                                         0.0
dtype: float64

In [27]:
df.head()

,Country,srcYear,Type of scheduled commercial banks,Bank name,Cash in hand,Balances with Reserve Bank of India(RBI),Balances with banks in India,Money at call and short notice,Balances with banks outside India,Investments,...,Fixed assets,Premises by fixed assets,Fixed assets under construction,Other fixed assets,Other assets,Interest accrued,Tax paid by other assets,Stationery and Stamps by other assets,Others by other assets,Total assets
0,India,2023-24,FOREIGN BANKS,AB BANK LIMITED,0.395063,6.236989,121.908369,430.216550,151.728852,74.26462,...,0.341193,1032.148504,7.822400,0.341193,13.292653,3.629779,0.128255,0.008464,9.521620,436.387817
1,India,2023-24,FOREIGN BANKS,AMERICAN EXPRESS BANKING CORP.,646.651330,363.050800,6.175600,430.216550,2415.698606,4609.90750,...,388.151100,1032.148504,7.822400,388.151100,1027.402100,17.302400,95.484600,1.435000,914.615100,11113.410200
2,India,2023-24,FOREIGN BANKS,AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED,0.076700,429.032300,585.548900,430.216550,602.421500,17757.72550,...,27.814900,1032.148504,7.822400,27.814900,4658.739000,232.410900,81.717500,16.311500,4328.299100,27939.114900
3,India,2023-24,FOREIGN BANKS,"BANK OF AMERICA , NATIONAL ASSOCIATION",3.566503,3960.120205,16.268482,4255.612041,68.045508,60159.60979,...,177.793697,1032.148504,18.422394,159.371303,10705.003340,722.582426,197.483168,1.435000,9784.937748,106784.003400
4,India,2023-24,FOREIGN BANKS,BANK OF BAHRAIN & KUWAIT B.S.C.,1.162100,92.236000,2.798600,285.610600,53.116900,529.45280,...,21.388000,16.560000,0.194600,4.633400,137.968700,11.382800,5.633500,0.000600,120.951800,2558.061900

In [28]:
df.to_csv('cleaned_bank_data.csv', index=False)
print("CSV file exported successfully!")

CSV file exported successfully!

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1775 entries, 0 to 1774
Data columns (total 37 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Country                                            1775 non-null   object
 1   srcYear                                            1775 non-null   object
 2   Type of scheduled commercial banks                 1775 non-null   object
 3   Bank name                                          1775 non-null   object
 4   Cash in hand                                       1775 non-null   float64
 5   Balances with Reserve Bank of India(RBI)           1775 non-null   float64
 6   Balances with banks in India                       1775 non-null   float64
 7   Money at call and short notice                     1775 non-null   float64
 8   Balances with banks outside India                  1775 non-null   float64
 9   Investments                                        1775 non-null   float64
 10  Investments in India                               1775 non-null   float64
 11  Investments on government securities in India      1775 non-null   float64
 12  Investments on shares in India                     1775 non-null   float64
 13  Investments on debentures and bonds in India       1775 non-null   float64
 14  Other investments in India                         1775 non-null   float64
 15  Advances                                           1775 non-null   float64
 16  Bills purchased and discounted                     1775 non-null   float64
 17  Cash credits, overdrafts and loans                 1775 non-null   float64
 18  Term loans                                         1775 non-null   float64
 19  Advances secured by tangible assets                1775 non-null   float64
 20  Advances covered by bank or government guarantees  1775 non-null   float64
 21  Unsecured advances                                 1775 non-null   float64
 22  Advances in India                                  1775 non-null   float64
 23  Advances in priority sectors in India              1775 non-null   float64
 24  Advances in public sectors in India                1775 non-null   float64
 25  Advances in banks in India                         1775 non-null   float64
 26  Other advances in India                            1775 non-null   float64
 27  Fixed assets                                       1775 non-null   float64
 28  Premises by fixed assets                           1775 non-null   float64
 29  Fixed assets under construction                    1775 non-null   float64
 30  Other fixed assets                                 1775 non-null   float64
 31  Other assets                                       1775 non-null   float64
 32  Interest accrued                                   1775 non-null   float64
 33  Tax paid by other assets                           1775 non-null   float64
 34  Stationery and Stamps by other assets              1775 non-null   float64
 35  Others by other assets                             1775 non-null   float64
 36  Total assets                                       1775 non-null   float64
dtypes: float64(33), object(4)
memory usage: 513.2+ KB

In [34]:
from sqlalchemy import create_engine
# MySQL connection details
username = 'root'
password = 'vighnesh2580'
host = 'localhost'
port = '3306'
database = 'commercial_bank_data'

# Create connection engine
engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)
# Load your cleaned CSV file
df = pd.read_csv("cleaned_bank_data.csv")

# Store data into MySQL table
df.to_sql(
    name='bank_data',
    con=engine,
    if_exists='replace',   # replace / append
    index=False
)

print("Data successfully stored in MySQL!")

Data successfully stored in MySQL!